# ~~~~~~~~~~~~~~~~~~ Stage 1: The Final Production Image ~~~~~~~~~~~~~~~~~~
# This stage assembles the final, small image from the artifacts
FROM node:18-alpine AS final

# Set the environment to production and define the working directory.
ENV NODE_ENV=production
WORKDIR /app

COPY ./node_modules ./node_modules
COPY ./package.json ./package.json
COPY ./apps/backend ./apps/backend

EXPOSE 8000

WORKDIR /app/apps/backend
CMD ["yarn", "start"]