#!/bin/sh
# entrypoint.sh

# Find the main JavaScript file generated by Create React App.
main_js_file=$(find /usr/share/nginx/html/static/js -name "main.*.js")

# Check if the file was found
if [ -z "$main_js_file" ]; then
  echo "Error: main.*.js file not found!"
  exit 1
fi

echo "Found main JS file: $main_js_file"

# Replace the placeholder with the runtime environment variable.
# Note: You need to define REACT_APP_API_BASE_URL in your Kubernetes Deployment YAML.
echo "Substituting environment variables..."
sed -i "s|__REACT_APP_API_BASE_URL__|$REACT_APP_API_BASE_URL|g" "$main_js_file"

echo "Substitution complete. Starting Nginx..."

# Start the NGINX server in the foreground.
# This is the original CMD from the NGINX base image.
exec nginx -g 'daemon off;'
