# 3. The updated Ingress resource, now pointing to the local proxy services.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexusgear-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # Rule for the Backend API
  - host: "nexusgear-backend.aryan-rai.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Point to the proxy service in the 'default' namespace
            name: backend-proxy-service
            port:
              # This port number must match the port on the target service
              number: 80
  # Rule for the Frontend Application
  - host: "nexusgear.aryan-rai.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Point to the proxy service in the 'default' namespace
            name: frontend-proxy-service
            port:
              # This port number must match the port on the target service
              number: 80
